import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { getBackend } from './actions';
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'PÉK Infinity',
  description: 'Generated by create next app',
};

export const dynamic = 'force-dynamic';

export default async function RootLayoutServer({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  'use server';
  const apiBasePath = await getBackend({ preferredNetwork: 'public' });
  return (
    <html lang='hu'>
      <body className={inter.className}>
        <Providers apiBasePath={apiBasePath}>{children}</Providers>
      </body>
    </html>
  );
}
