/* tslint:disable */
/* eslint-disable */
/**
 * PÉK API
 * Profiles and Groups
 *
 * The version of the OpenAPI document: v4
 * Contact: hello@kir-dev.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

