pipeline:
  identifier: Build_tomitheninja_pek_infinity_1743776641843
  name: Build pek-infinity
  orgIdentifier: default
  projectIdentifier: pekinfinity
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1743775567739
        repoName: tomitheninja/pek-infinity
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: lint
                  name: lint
                  spec:
                    command: npm run lint
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    command: npm run build
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
